
POST /user/signup HTTP/1.1
Host: gr2-hr-management-be.onrender.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsImVtYWlsIjoiaGFpMzA0QGdtYWlsLmNvbSIsImlhdCI6MTcxMTAzNzc5NH0.tjwuXi31Bn3BStmD9vW47KPm4QrgpKtNovqxEpAgEKo

{
    "id": "304",
    "firstName": "Hai",
    "lastName": "Le",
    "email": "hai304@gmail.com",
    "gender": "Male",
    "phone": "702917344",
    "address": "78K4Cong65 Hoa",
    "department": "IT",
    "position": "Full Stack",
    "password": "hoanghai2002",
    "role": "user"
}


###POST /user/signup HTTP/1.1
POST /user/login HTTP/1.1
Host: gr2-hr-management-be.onrender.com
Content-Type: application/json

{
    "email": "hai304@gmail.com",
    "password": "hoanghai2002"
}


###
GET /employeedata HTTP/1.1
Host: gr2-hr-management-be.onrender.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImhhaTI4MDIyMDAyQGdtYWlsLmNvbSIsImlhdCI6MTcxMTAzODU3NH0.XBYAmce7RkKkDz7-sI-e5iSocc5brBvL6SB8AdJVkjM

###
GET /employeepayrolldata HTTP/1.1
Host: gr2-hr-management-be.onrender.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImhhaTI4MDIyMDAyQGdtYWlsLmNvbSIsImlhdCI6MTcxMTA0MjM0NH0.R8rQG6YtblWD2fmXLj__8fYMSXeqyQK7zw70264h_3g